# Generated by Django 3.2.9 on 2024-03-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
